export const copy = {
  app: {
    name: 'Rango Social',
    tagline: 'Onde sua tropa descobre os melhores rolês',
  },
  nav: {
    home: 'Home',
    ranking: 'Top da galera',
    review: 'Mandar a real',
    notifications: 'Fofoca',
    profile: 'Minha área',
  },
  cta: {
    reviewPrimary: 'Mandar a real',
    reviewAlt: 'Dar o papo',
    reviewNoScore: 'Só colei lá',
    reviewNoScoreAlt: 'Dei um pulo',
    publish: 'Lançar a braba 🚀',
    publishing: 'Lançando a braba…',
    published: 'Mandou bem! 🔥',
  },
  badges: {
    trending: 'Tá bombando',
    hype: 'No hype',
    viral: 'Virou febre',
  },
  reviews: {
    negativeFlop: 'Flopou',
    negativeAlt: 'Não tankei',
    negativeLetdown: 'Decepcionou',
    positiveAmassed: 'Amassei',
    positiveLocal: 'Rango de cria',
    positiveAesthetic: 'Muito aesthetic',
    positiveVibes: '100% vibes',
  },
  social: {
    friends: 'Bonde',
    friendsAlt: 'Chegados',
    friendsAlt2: 'Parça',
    friendsAlt3: 'Cria',
    follow: 'Acompanhar',
    following: 'Tá na minha lista',
    unfollow: 'Deixar de acompanhar',
  },
  groups: {
    title: 'Tropas',
    label: 'Tropa',
    labelAlt: 'Squad',
    labelAlt2: 'Gangue',
    create: 'Criar tropa',
    open: 'Tropa aberta',
    closed: 'Tropa fechada',
  },
  wishlist: {
    title: 'Quero ir',
    alt: 'Salvei',
    alt2: 'Na mira',
  },
  lists: {
    title: 'Minhas listas',
    alt: 'Meus rolês',
    create: 'Nova lista',
  },
  ranking: {
    title: 'Top da galera',
    subtitle: 'Quem tá no topo',
    filterEveryone: 'Todo mundo',
    filterFollowing: 'Só os de verdade',
    filterGroups: 'Minha tropa',
  },
  notifications: {
    title: 'Fofoca',
    subtitle: 'O que tá rolando',
    today: 'Hoje',
    yesterday: 'Ontem',
    week: 'Esta semana',
  },
  profile: {
    title: 'Minha área',
    my: 'Meu perfil',
    tabReviews: 'Reviews',
    tabPhotos: 'Fotos',
    tabVibes: 'Vibe Checks',
    tabLikes: 'Curtidas',
    actionLists: '📝 Listas',
    actionGroups: '👥 Tropas',
    actionWishlist: '💾 Quero ir',
    actionBadges: '🏆 Conquistas',
  },
  comments: {
    title: 'Resenha',
    alt: 'Papo',
    likeLabel: 'Amei',
    likeAlt: 'Fogo',
    likeAlt2: 'Mandou bem',
  },
  search: {
    title: 'Achar rango',
    subtitle: 'Onde vou?',
    placeholder: 'Cadê meu rango hoje?',
    filtersTitle: 'Refinar o rolê',
  },
  settings: {
    title: 'Ajustes',
    alt: 'Meu esquema',
    logout: 'Vazar',
    logoutAlt: 'Fui',
  },
  loading: {
    default: 'Preparando o rolê…',
    short: 'Só um seg…',
    errorDefault: 'Deu ruim',
    errorAlt: 'Algo flopou',
    errorRetry: 'Tentar de novo',
    emptyDefault: 'Nenhum review ainda',
    emptyNoFriends: 'Seu bonde tá quieto. Bora seguir uns crias?',
    emptyNoNotifications: 'Tá zero fofoca por aqui',
  },
  vibeCheck: {
    title: 'Como tá o rolê?',
    cta: 'Como tá?',
    statusNow: 'Agora',
  },
  roulette: {
    cta: '🎲 Onde vou hoje?',
    anywhere: 'Toquei o fodase',
    again: 'De novo 🎲',
    letsGo: 'Bora!',
  },
  price: {
    cheap: 'Baratin',
    moderate: 'Na média',
    expensive: 'Tá caro',
    luxury: 'Luxo',
  },
  onboarding: {
    welcome: 'Bem-vindo ao Rango Social 👋',
    subtitle: 'Onde sua tropa descobre os melhores rolês.',
    chooseStyle: 'Escolhe seu estilo',
    styleFriends: '🍔 Sou do bonde',
    styleInfluencer: '📸 Influencer',
    styleFoodie: '🍽️ Foodie',
    styleCheap: '💸 Baratin',
    chooseCity: 'Escolhe sua cidade',
    useLocation: 'Usar minha localização',
    followPeople: 'Segue uns crias',
    skip: 'Pular',
    done: 'Bora explorar! 🚀',
  },
  streak: {
    label: '🔥 %d dias',
    warning: 'Falta 1 review pra manter seu streak! 🔥',
    badgesTitle: 'Conquistas',
    badgeEarned: 'Nova conquista: %s 🏆',
  },
  generic: {
    save: 'Salvar',
    share: 'Compartilhar',
    cancel: 'Cancelar',
    done: 'Pronto',
    next: 'Próximo',
    back: 'Voltar',
    edit: 'Editar',
    delete: 'Apagar',
  },
  stories: {
    title: 'Stories',
    composerTitle: 'Lançar Story 📸',
    viewerTitle: 'Visualizadores',
    expireNotice: 'Some em 24h',
  },
  illness: {
    button: 'Passei mal aqui 🤢',
    title: 'Relatar Mal-estar',
    symptomLabel: 'O que sentiu?',
    mealDateLabel: 'Quando comeu?',
    notePlaceholder: 'Algum detalhe extra? (opcional)',
    submit: 'Relatar anonimamente',
    warning: '⚠️ %d relatos de mal-estar nos últimos 90 dias',
  },
  duel: {
    title: 'Bora um duelo? 🥊',
    subtitle: 'A vs B: quem mandou melhor?',
    questionSabor: 'Quem tem o melhor sabor?',
    questionAtendimento: 'Quem atende melhor?',
    questionCustoBeneficio: 'Quem tem o melhor custo-benefício?',
    leaderboardTitle: 'Top do Bairro',
    leaderboardGlobal: 'Global',
    leaderboardBonde: 'No meu bonde',
  },
  ai: {
    chatTitle: 'IA do Rango 🤖',
    chatPlaceholder: 'Pergunta onde ir, o que comer...',
    agentChoose: 'Prefere que a IA escolha? 🤖',
  },
} as const

export type CopyType = typeof copy
